class FootballMapper {
  /// Consolidated map for Teams, Competitions, Areas, and Statuses
  static const Map<String, String> translations = {
    // --- AREAS (Countries & Continents) ---
    "World": "العالم",
    "Europe": "أوروبا",
    // --- COMPETITIONS ---
    "Premier League": "الدوري الإنجليزي الممتاز",
    "Primera Division": "الدوري الإسباني",
    "Serie A": "الدوري الإيطالي",
    "Ligue 1": "الدوري الفرنسي",
    "Bundesliga": "الدوري الألماني",
    "UEFA Champions League": "دوري أبطال أوروبا",
    "FIFA World Cup": "كأس العالم",

    // --- MATCH STATUSES ---
    "SCHEDULED": "مجدولة",
    "TIMED": "محددة بوقت",
    "IN_PLAY": "مباشرة",
    "PAUSED": "متوقفة",
    "FINISHED": "انتهت",
    "POSTPONED": "مؤجلة",
    "SUSPENDED": "معلقة",
    "CANCELLED": "ملغية",

    // --- PREMIER LEAGUE (PL) ---
    "Arsenal FC": "أرسنال",
    "Aston Villa FC": "أستون فيلا",
    "AFC Bournemouth": "بورنموث",
    "Brentford FC": "برينتفورد",
    "Brighton & Hove Albion FC": "برايتون",
    "Burnley FC": "بيرنلي",
    "Chelsea FC": "تشيلسي",
    "Crystal Palace FC": "كريستال بالاس",
    "Everton FC": "إيفرتون",
    "Fulham FC": "فولهام",
    "Liverpool FC": "ليفربول",
    "Manchester City FC": "مانشستر سيتي",
    "Manchester United FC": "مانشستر يونايتد",
    "Newcastle United FC": "نيوكاسل يونايتد",
    "Nottingham Forest FC": "نوتينغهام فورست",
    "Tottenham Hotspur FC": "توتنهام",
    "West Ham United FC": "وست هام",
    "Wolverhampton Wanderers FC": "وولفرهامبتون",
    "Luton Town FC": "لوتون تاون",
    "Sheffield United FC": "شيفيلد يونايتد",

    // --- LA LIGA (PD) ---
    "Real Madrid CF": "ريال مدريد",
    "FC Barcelona": "برشلونة",
    "Atlético Madrid": "أتلتيكو مدريد",
    "Real Sociedad": "ريال سوسيداد",
    "Real Betis": "ريال بيتيس",
    "Sevilla FC": "إشبيلية",
    "Villarreal CF": "فياريال",
    "Valencia CF": "فالنسيا",
    "Athletic Club": "أتلتيك بيلباو",
    "Girona FC": "جيرونا",
    "Celta de Vigo": "سيلتا فيغو",
    "RCD Mallorca": "مايوركا",
    "CA Osasuna": "أوساسونا",
    "Getafe CF": "خيتافي",
    "Rayo Vallecano": "رايو فايكانو",
    "Deportivo Alavés": "ألافيس",
    "Granada CF": "غرناطة",
    "UD Las Palmas": "لاس بالماس",
    "Cádiz CF": "قادش",
    "UD Almería": "ألميريا",

    // --- SERIE A (SA) ---
    "Inter Milan": "إنتر ميلان",
    "Juventus FC": "يوفنتوس",
    "AC Milan": "ميلان",
    "SSC Napoli": "نابولي",
    "AS Roma": "روما",
    "SS Lazio": "لاتسيو",
    "ACF Fiorentina": "فيورنتينا",
    "Atalanta BC": "أتالانتا",
    "Bologna FC": "بولونيا",
    "Torino FC": "تورينو",
    "US Monza": "مونزا",
    "Genoa CFC": "جنوى",
    "US Lecce": "ليتشي",
    "Udinese Calcio": "أودينيزي",
    "Hellas Verona FC": "هيلاس فيرونا",
    "Empoli FC": "إمبولي",
    "US Salernitana 1919": "ساليرنيتانا",
    "Sassuolo Calcio": "ساسولو",
    "Frosinone Calcio": "فروزينوني",
    "Cagliari Calcio": "كالياري",

    // --- BUNDESLIGA (BL1) ---
    "FC Bayern München": "بايرن ميونخ",
    "Borussia Dortmund": "بوروسيا دورتموند",
    "Bayer 04 Leverkusen": "باير ليفركوزن",
    "RB Leipzig": "لايبزيج",
    "Eintracht Frankfurt": "آينتراخت فرانكفورت",
    "VfB Stuttgart": "شتوتغارت",
    "SC Freiburg": "فرايبورج",
    "VfL Wolfsburg": "فولفسبورج",
    "TSG 1899 Hoffenheim": "هوفنهايم",
    "Borussia Mönchengladbach": "بوروسيا مونشنغلادباخ",
    "1. FC Union Berlin": "يونيون برلين",
    "SV Werder Bremen": "فيردر بريمن",
    "FC Augsburg": "أوجسبورج",
    "1. FSV Mainz 05": "ماينز",
    "1. FC Köln": "كولن",
    "VfL Bochum 1848": "بوخوم",
    "SV Darmstadt 98": "دارمشتات",
    "1. FC Heidenheim 1846": "هايدنهايم",

    // --- LIGUE 1 (FL1) ---
    "Paris Saint-Germain FC": "باريس سان جيرمان",
    "Olympique de Marseille": "مارسيليا",
    "AS Monaco FC": "موناكو",
    "Lille OSC": "ليل",
    "OGC Nice": "نيس",
    "Olympique Lyonnais": "ليون",
    "Stade Rennais FC 1901": "رين",
    "RC Lens": "لانس",
    "Stade de Reims": "ريمس",
    "FC Lorient": "لوريان",
    "Stade Brestois 29": "بريست",
    "Toulouse FC": "تولوز",
    "Montpellier HSC": "مونبلييه",
    "RC Strasbourg Alsace": "ستراسبورغ",
    "FC Nantes": "نانت",
    "Le Havre AC": "لو هافر",
    "FC Metz": "ميتز",
    "Clermont Foot 63": "كليرمونت",

    // --- WORLD CUP (WC) 2026 ---
    "USA": "الولايات المتحدة",
    "Mexico": "المكسيك",
    "Canada": "كندا",
    "Argentina": "الأرجنتين",
    "Brazil": "البرازيل",
    "France": "فرنسا",
    "Germany": "ألمانيا",
    "Spain": "إسبانيا",
    "England": "إنجلترا",
    "Portugal": "البرتغال",
    "Italy": "إيطاليا",
    "Belgium": "بلجيكا",
    "Netherlands": "هولندا",
    "Croatia": "كرواتيا",
    "Morocco": "المغرب",
    "Senegal": "السنغال",
    "Algeria": "الجزائر",
    "Uruguay": "أوروغواي",
    "Colombia": "كولومبيا",
    "Ecuador": "الإكوادور",
    "Nigeria": "نيجيريا",
    "Ivory Coast": "ساحل العاج",
    "Tunisia": "تونس",
    "Qatar": "قطر",
    "Jordan": "الأردن",
    "Uzbekistan": "أوزبكستان",

    // --- NON-TOP 5 CHAMPIONS LEAGUE (CL) ---
    "PSV Eindhoven": "بي إس في آيندهوفن",
    "Ajax": "أياكس",
    "Feyenoord": "فينورد",
    "Sporting CP": "سبورتينغ لشبونة",
    "Sport Lisboa e Benfica": "بنفيكا",
    "FC Porto": "بورتو",
    "Club Brugge": "كلوب بروج",
    "Galatasaray SK": "غالطة سراي",
    "Fenerbahce": "فنربخشة",
    "Celtic FC": "سلتيك",
    "Rangers FC": "رينجرز",
    "Red Bull Salzburg": "ريد بول سالزبورغ",
    "Shakhtar Donetsk": "شاختار دونيتسك",
    "Sparta Praha": "سبارتا براغ",
    "Slavia Praha": "سلافيا براغ",
    "Olympiacos FC": "أولمبياكوس",
    "PAOK FC": "باوك",
    "Panathinaikos FC": "باناثينايكوس",
    "Bodo/Glimt": "بودو غليمت",
    "FC Copenhagen": "كوبنهاجن",
  };

  /// Main translation logic
  static String translate(String? key) {
    if (key == null || key.isEmpty) return "";
    return translations[key] ?? key;
  }
}