// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZNudESNhabe3Puw3tSpNQPtER9H9PWs',
    appId: '1:1052642368571:web:5db333f257dfa6309e101e',
    messagingSenderId: '1052642368571',
    projectId: 'trivio-4878e',
    authDomain: 'trivio-4878e.firebaseapp.com',
    storageBucket: 'trivio-4878e.firebasestorage.app',
    measurementId: 'G-NXG24RJ26F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnEeEE3EEBB8n8C2XqtF7WtpLz5nazVes',
    appId: '1:1052642368571:android:ee5bdc0a975c36989e101e',
    messagingSenderId: '1052642368571',
    projectId: 'trivio-4878e',
    storageBucket: 'trivio-4878e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBygwkSvjfnWPdHb_jOarrk4AzYu0EO7U',
    appId: '1:1052642368571:ios:e8c7616f38d2d05c9e101e',
    messagingSenderId: '1052642368571',
    projectId: 'trivio-4878e',
    storageBucket: 'trivio-4878e.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBygwkSvjfnWPdHb_jOarrk4AzYu0EO7U',
    appId: '1:1052642368571:ios:e8c7616f38d2d05c9e101e',
    messagingSenderId: '1052642368571',
    projectId: 'trivio-4878e',
    storageBucket: 'trivio-4878e.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpZNudESNhabe3Puw3tSpNQPtER9H9PWs',
    appId: '1:1052642368571:web:5bca423b0cc91a2d9e101e',
    messagingSenderId: '1052642368571',
    projectId: 'trivio-4878e',
    authDomain: 'trivio-4878e.firebaseapp.com',
    storageBucket: 'trivio-4878e.firebasestorage.app',
    measurementId: 'G-LTQVXQ5R4X',
  );

}